variables:
  #service connection string for production func
  azureSubscriptionProd: myAppConnectionString

  #service connection string for QA func
  azureSubscriptionQA: myConnectionStringQA
  
trigger:
- master

stages:
- stage: Build
  displayName: Build Stage

  jobs:
  - job:
    displayName: Build
    pool:
      vmImage: ubuntu-16.04
    steps:
    - task: UsePythonVersion@0
      displayName: "Setting python version to 3.7 as required by functions"
      inputs:
        versionSpec: '3.7'
        architecture: 'x64'
    - bash: |
        if [ -f extensions.csproj ]
        then
            dotnet build extensions.csproj --output ./bin
        fi
        pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
    - task: ArchiveFiles@2
      displayName: "Archive files"
      inputs:
        rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
        includeRootFolder: false
        archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'
        artifactName: 'drop' 
- stage: Test
  displayName: Test
  jobs:
  - job:
    displayName: Test
    steps:
    - script: python -m pip install truffleHog
      displayName: "Install TruffleHog"
    - script: truffleHog --regex --entropy=False https://github.com/dgilmore/pythonAppBP.git  
      displayName: "run truffleHog"
- stage: Production
  displayName: Deploy to Production
  dependsOn: Build
  condition: succeeded()

  jobs:
  - job: 
    displayName: deploy to production
    pool:
      vmImage: ubuntu-16.04
    steps:
    - task: DownloadPipelineArtifact@2
      inputs: 
        artifact: drop
        path: $(Build.SourcesDirectory)/bin
    - task: AzureFunctionApp@1
      displayName: 'azure func production deploy'
      inputs:
        azureSubscription: $(azureSubscriptionProd)
        appType: functionAppLinux
        appName: 'bpapp'
        package: '$(Build.SourcesDirectory)/bin/drop'
    



